### PR TITLE
Adding support for a message history.

### PR DESCRIPTION
**Pull request by DxsSucuk**
This PR add support for passing more then 1 single message to Chat-GPT

### CODE REVIEW

**Comment by DxsSucuk** [comment]
@LiLittleCat Will this be merged?

**Comment by LiLittleCat** [comment]
Hi there, @DxsSucuk! Thanks for your help with the project. I was wondering if you could also add a test to demonstrate how to use the functionality in [ChatGPTTest.java](https://github.com/LiLittleCat/ChatGPT/blob/main/src/test/java/ChatGPTTest.java)? I think it would be helpful for people to have a clear example of how to utilize this feature in their code. Thank you!

**Comment by DxsSucuk** [comment]
Done @LiLittleCat, also modified my changes to make everything a bit more backwards compatible.

**Comment by LiLittleCat** [comment]
@DxsSucuk LGTM, thanks for your contribution.

**Pull request merged**
